# schemachange/connections.toml
[default]
account = "{{ secrets.SF_ACCOUNT }}"
user = "{{ secrets.SF_USER_NAME }}"
password = "{{ secrets.SF_PASSWORD }}"
role = "{{ secrets.SF_ROLE }}"
warehouse = "{{ secrets.SF_WAREHOUSE }}"
database = "{{ secrets.SF_DATABASE }}"
