name: snowflake-devops-workflow

on:
  push:
    branches:
      - main
    paths:
      - 'schemachange/scripts/**'
      - 'schemachange/connections.toml'

  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Set permissions for connections.toml
        run: |
          chmod 600 "$GITHUB_WORKSPACE/schemachange/connections.toml"
        # Only run this step if connections.toml exists, good for robustness
        # if: success() || failure() # Or use always() if you want it to always run
        # if: steps.checkout.outcome == 'success' # A more specific condition

      - name: Run schemachange
        run: |
          pip install schemachange
          schemachange deploy \
            -f "$GITHUB_WORKSPACE/schemachange/scripts" \
            --connections-file-path "$GITHUB_WORKSPACE/schemachange/connections.toml" \
            --connection-name default \
            -c "$SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
            --connection-name default \
            -c "$SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
