name: snowflake-devops-workflow

on:
  push:
    branches:
      - main
    paths:
      - 'schemachange/scripts/**'
      - 'schemachange/connections.toml'

  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Set permissions for connections.toml
        run: |
          chmod 600 "$GITHUB_WORKSPACE/schemachange/connections.toml"

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USER_NAME: ${{ secrets.SF_USERNAME }} # Ensure this matches your TOML and Secret name exactly
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          pip install schemachange
          schemachange deploy \
            -f "$GITHUB_WORKSPACE/schemachange/scripts" \
            --connections-file-path "$GITHUB_WORKSPACE/schemachange/connections.toml" \
            --connection-name default \
            -c "$SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
            --connection-name default \
            -c "$SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
