name: snowflake-devops-workflow

# Controls when the action will run.
on:
  push:
    branches:
      - main
    paths:
      - 'schemachange/scripts/**'
      - 'schemachange/connections.toml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2 # Or v4, both behave similarly for default pathing

      - name: Use Python 3.8.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USER_NAME: ${{ secrets.SF_USER_NAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          pip install schemachange
          schemachange deploy \
            -f "$GITHUB_WORKSPACE/schemachange/scripts" \
            --connections-file-path "$GITHUB_WORKSPACE/schemachange/connections.toml" \
            --connection-name default \
            -c "$SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY" \
            --create-change-history-table
